name: check_clang-format

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'false'
    
    - name: Updating clang (clang-format)
      shell: bash
      run: |
        sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main' && \
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc && \
        sudo apt-mark hold grub-efi-amd64-signed && sudo apt-get update --fix-missing && sudo apt-get upgrade && sudo apt-get install clang-format-15 && \
        sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-17 1000
      
    - name: Check clang-format version
      shell: bash
      run: clang-format --version
    
    - name: Check format
      shell: bash
      working-directory: ${{github.workspace}}
      run: ./verify_clang_format.sh
    