name: CMake_macos

on:
  push:
  pull_request:
    types: [opened, reopened]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2
      id: cpu-cores
    
    - name: Handling project dependencies
      shell: bash
      working-directory: ${{github.workspace}}/deps
      run: |
        cmake . -D CMAKE_BUILD_TYPE=$BUILD_TYPE
        cmake --build . -j ${{steps.cpu-cores.outputs.count}} --config $BUILD_TYPE
    
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D FGE_DEPS_PATH="deps/libs"

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . -j ${{steps.cpu-cores.outputs.count}} --config $BUILD_TYPE

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C $BUILD_TYPE --verbose
