name: CMake_linux_gcc_64bit

on:
  push:
  pull_request:
    types: [opened, reopened]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2
      id: cpu-cores
    
    - name: Install gcc
      run: sudo apt-get update && sudo apt-get install gcc-11 g++-11
    
    - name: Install dependencies
      run: |
        sudo apt-get install libx11-dev libxrandr-dev libudev-dev \
        libglu1-mesa-dev freeglut3-dev mesa-common-dev libflac-dev libogg-dev \
        libvorbis-dev libopenal-dev libxcursor-dev
    
    - name: Handling project dependencies
      shell: bash
      working-directory: ${{github.workspace}}/deps
      run: |
        cmake . -D CMAKE_BUILD_TYPE=$BUILD_TYPE
        cmake --build . -j ${{steps.cpu-cores.outputs.count}} --config $BUILD_TYPE
    
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -D CMAKE_C_COMPILER=gcc-11 -D CMAKE_CXX_COMPILER=g++-11 -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D FGE_DEPS_PATH="deps/libs"
    
    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . -j ${{steps.cpu-cores.outputs.count}} --config $BUILD_TYPE
    
    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C $BUILD_TYPE --verbose
    
    - name: Installing
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --install .
    
    - uses: actions/upload-artifact@v4
      with:
        name: FastEngine-linux-64
        path: ${{github.workspace}}/install/FastEngine*
        if-no-files-found: error
        retention-days: 3
        compression-level: 9
